name: Android Internal Testing Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "lib/**"
      - "android/**"
      - "pubspec.yaml"
      - ".github/workflows/android-internal.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PACKAGE_NAME: com.appweavers.upnow
      AAB_PATH: build/app/outputs/bundle/release/app-release.aab
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      # Tests disabled per request

      - name: Decode keystore (from secret)
        shell: bash
        run: |
          set -e
          if [ -z "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "ANDROID_KEYSTORE_BASE64 is empty; aborting" >&2
            exit 1
          fi
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create android/key.properties
        shell: bash
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=../app/upload-keystore.jks
          EOF

      - name: Build Android App Bundle (release)
        run: flutter build appbundle --release

      - name: Upload to Google Play - Internal testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: ${{ env.AAB_PATH }}
          track: internal
          status: completed


